version: '2'

services:
  web-maven:
    build: workspace/.
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/workspace
    networks:
      - alura-web-network
    working_dir: /workspace
    command: bash -c "cd lojaweb && mvn jetty:run"

networks:
  alura-web-network:
    driver: bridge